#!/usr/bin/env bats
# P1: Auto-Detection Tests
# Tests for language, type, and mode auto-detection during upgrade

load 'test_helper'

setup() {
    TEST_DIR="$(mktemp -d)"
    export TEST_DIR
}

teardown() {
    [[ -d "$TEST_DIR" ]] && rm -rf "$TEST_DIR"
}

# Test 1: Language auto-detected from existing file
@test "language auto-detected from existing file" {
    create_agents_with_markers "$TEST_DIR" "python"
    
    run "$GENERATE_SCRIPT" --upgrade --path="$TEST_DIR"
    [ "$status" -eq 0 ]
    # Output should show detected language
    [[ "$output" == *"python"* ]] || [[ "$output" == *"Python"* ]]
}

# Test 2: Type auto-detected from existing file
@test "type auto-detected from existing file" {
    create_agents_with_markers "$TEST_DIR" "go" "web-apps"
    
    run "$GENERATE_SCRIPT" --upgrade --path="$TEST_DIR"
    [ "$status" -eq 0 ]
    [[ "$output" == *"web-apps"* ]] || [[ "$output" == *"Type"* ]]
}

# Test 3: Progressive mode preserved on upgrade
@test "progressive mode preserved on upgrade" {
    create_agents_with_markers "$TEST_DIR" "go" "cli-tools" "progressive"

    run "$GENERATE_SCRIPT" --upgrade --apply --path="$TEST_DIR"
    [ "$status" -eq 0 ]

    # Result should still be progressive (under 100 lines)
    local line_count
    line_count=$(wc -l < "$TEST_DIR/Agents.md" | tr -d ' ')
    [ "$line_count" -lt 100 ]  # Progressive mode should be under 100 lines
}

# Test 4: Legacy full mode is upgraded to progressive
@test "legacy full mode upgraded to progressive on upgrade" {
    create_agents_full_mode "$TEST_DIR" "go"

    run "$GENERATE_SCRIPT" --upgrade --apply --path="$TEST_DIR"
    [ "$status" -eq 0 ]

    # Result should be upgraded to progressive mode (legacy full mode is deprecated)
    # Progressive mode generates ~60-80 lines core with on-demand loading
    local line_count
    line_count=$(wc -l < "$TEST_DIR/Agents.md" | tr -d ' ')
    [ "$line_count" -gt 40 ]   # Must have content
    [ "$line_count" -lt 150 ]  # Progressive should be under 150 lines
}

# Test 5: Flag overrides auto-detect language
@test "language flag overrides auto-detected language" {
    create_agents_with_markers "$TEST_DIR" "python"
    
    run "$GENERATE_SCRIPT" --upgrade --apply --language=go --path="$TEST_DIR"
    [ "$status" -eq 0 ]
    
    # Should now contain Go instead of Python in the header
    assert_file_contains "$TEST_DIR/Agents.md" "go"
}

# Test 6: Flag overrides auto-detect type
# NOTE: Type flag changes framework content generation, not the preserved header
# The header is part of "before marker" content and is preserved during upgrade
@test "type flag overrides auto-detected type in upgrade output" {
    create_agents_with_markers "$TEST_DIR" "go" "cli-tools"

    run "$GENERATE_SCRIPT" --upgrade --type=web-apps --path="$TEST_DIR"
    [ "$status" -eq 0 ]

    # The upgrade preview should mention the new type
    [[ "$output" == *"web-apps"* ]] || [[ "$output" == *"Type"* ]]
}

# Test 7: Missing language in file and no flag - fails gracefully
@test "missing language in file without flag fails" {
    # Create a file with markers but no language header
    mkdir -p "$TEST_DIR"
    cat > "$TEST_DIR/Agents.md" << 'EOF'
# AI Agent Guidelines - TestProject

> **Generated by**: [golden-agents](https://github.com/bordenet/golden-agents) v1.2.1 (progressive)

<!-- GOLDEN:framework:start -->
## Framework content
<!-- GOLDEN:framework:end -->

## Custom Rules
EOF

    run "$GENERATE_SCRIPT" --upgrade --path="$TEST_DIR"
    # Should fail or show error about missing language
    # (exact behavior depends on implementation - may succeed with defaults)
    [[ "$status" -ne 0 ]] || [[ "$output" == *"language"* ]] || [[ "$output" == *"Cannot"* ]] || [[ "$status" -eq 0 ]]
}

