#!/usr/bin/env bash
# Test helper functions for generate-agents.sh BATS tests

# Get the directory containing the script under test
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
GENERATE_SCRIPT="$SCRIPT_DIR/generate-agents.sh"

# Load bats helper libraries if available
if [[ -d "$SCRIPT_DIR/test/test_helper/bats-support" ]]; then
    load 'test_helper/bats-support/load'
fi
if [[ -d "$SCRIPT_DIR/test/test_helper/bats-assert" ]]; then
    load 'test_helper/bats-assert/load'
fi

# Create a minimal valid Agents.md WITH markers (v1.2.0+ style)
create_agents_with_markers() {
    local path="$1"
    local lang="${2:-go}"
    local type="${3:-cli-tools}"
    local mode="${4:-compact}"
    
    mkdir -p "$path"
    cat > "$path/Agents.md" << EOF
# AI Agent Guidelines - TestProject

> **Generated by**: [golden-agents](https://github.com/bordenet/golden-agents) v1.2.1 (${mode})
> **Last Updated**: 2026-02-01
> **Languages**: ${lang}
> **Type**: ${type}

Self-contained. Minimal high-signal tokens.
<!-- GOLDEN:framework:start -->

---

## Superpowers Integration

At the START of every conversation, run:

\`\`\`bash
node ~/.codex/superpowers-augment/superpowers-augment.js bootstrap
\`\`\`

<!-- GOLDEN:framework:end -->

---

## Project-Specific Rules

<!-- Add project-specific guidance below this line -->

### My Custom Rule
Always use feature branches for new work.

### Team Conventions
- PR requires 2 approvals
- Use conventional commits
EOF
}

# Create Agents.md WITHOUT markers (pre-v1.2.0 style)
create_agents_without_markers() {
    local path="$1"
    mkdir -p "$path"
    cat > "$path/Agents.md" << EOF
# AI Agent Guidelines - TestProject

## Some guidance
This file has no markers and was created before v1.2.0.

## Project Rules
- Do something
- Do something else
EOF
}

# Create Agents.md with full mode header (no "(compact)" in header)
create_agents_full_mode() {
    local path="$1"
    local lang="${2:-go}"
    
    mkdir -p "$path"
    cat > "$path/Agents.md" << EOF
# AI Agent Guidelines - TestProject

> **Generated by**: [golden-agents](https://github.com/bordenet/golden-agents) v1.2.1
> **Last Updated**: 2026-02-01
> **Languages**: ${lang}
> **Type**: cli-tools

<!-- GOLDEN:framework:start -->
## Framework content (full mode)
<!-- GOLDEN:framework:end -->

## Project-Specific Rules
Custom content here.
EOF
}

# Assert file contains pattern
assert_file_contains() {
    local file="$1"
    local pattern="$2"
    if ! grep -q "$pattern" "$file"; then
        echo "FAIL: File '$file' does not contain: $pattern" >&2
        echo "File contents:" >&2
        cat "$file" >&2
        return 1
    fi
}

# Assert file does NOT contain pattern
assert_file_not_contains() {
    local file="$1"
    local pattern="$2"
    if grep -q "$pattern" "$file"; then
        echo "FAIL: File '$file' should not contain: $pattern" >&2
        return 1
    fi
}

# Assert file exists
assert_file_exists() {
    local file="$1"
    if [[ ! -f "$file" ]]; then
        echo "FAIL: File '$file' does not exist" >&2
        return 1
    fi
}

# Assert directory exists
assert_dir_exists() {
    local dir="$1"
    if [[ ! -d "$dir" ]]; then
        echo "FAIL: Directory '$dir' does not exist" >&2
        return 1
    fi
}

# Get line count of file
get_line_count() {
    local file="$1"
    wc -l < "$file" | tr -d ' '
}

# Assert line count is within range
assert_line_count_between() {
    local file="$1"
    local min="$2"
    local max="$3"
    local count
    count=$(get_line_count "$file")
    if [[ "$count" -lt "$min" || "$count" -gt "$max" ]]; then
        echo "FAIL: File '$file' has $count lines, expected between $min and $max" >&2
        return 1
    fi
}

