#!/usr/bin/env bats
# P0: Upgrade Safety Tests - CRITICAL
# These tests ensure upgrades never destroy project-specific content

load 'test_helper'

setup() {
    # Create isolated temp directory for each test
    TEST_DIR="$(mktemp -d)"
    export TEST_DIR
}

teardown() {
    # Clean up temp directory
    [[ -d "$TEST_DIR" ]] && rm -rf "$TEST_DIR"
}

# Test 1: Upgrade on non-existent file fails
@test "upgrade fails when no Agents.md exists" {
    run "$GENERATE_SCRIPT" --upgrade --path="$TEST_DIR"
    [ "$status" -ne 0 ]
    [[ "$output" == *"No Agents.md found"* ]] || [[ "$output" == *"does not exist"* ]]
}

# Test 2: Upgrade on file WITHOUT markers REFUSES
@test "upgrade refuses file without markers" {
    create_agents_without_markers "$TEST_DIR"
    
    run "$GENERATE_SCRIPT" --upgrade --path="$TEST_DIR"
    [ "$status" -ne 0 ]
    [[ "$output" == *"lacks framework markers"* ]] || [[ "$output" == *"REFUSING"* ]] || [[ "$output" == *"markers"* ]]
}

# Test 3: Upgrade dry-run shows diff
@test "upgrade dry-run shows preview without changes" {
    create_agents_with_markers "$TEST_DIR"
    
    run "$GENERATE_SCRIPT" --upgrade --path="$TEST_DIR"
    [ "$status" -eq 0 ]
    [[ "$output" == *"PREVIEW"* ]] || [[ "$output" == *"preview"* ]] || [[ "$output" == *"No changes made"* ]]
}

# Test 4: Upgrade dry-run writes nothing
@test "upgrade dry-run does not modify file" {
    create_agents_with_markers "$TEST_DIR"
    local original_content
    original_content=$(cat "$TEST_DIR/Agents.md")
    
    run "$GENERATE_SCRIPT" --upgrade --path="$TEST_DIR"
    [ "$status" -eq 0 ]
    
    local new_content
    new_content=$(cat "$TEST_DIR/Agents.md")
    [ "$original_content" = "$new_content" ]
}

# Test 5: Upgrade --apply creates backup
@test "upgrade --apply creates backup file" {
    create_agents_with_markers "$TEST_DIR"
    
    run "$GENERATE_SCRIPT" --upgrade --apply --path="$TEST_DIR"
    [ "$status" -eq 0 ]
    [ -f "$TEST_DIR/Agents.md.backup" ]
}

# Test 6: Upgrade --apply modifies original
@test "upgrade --apply modifies original file" {
    create_agents_with_markers "$TEST_DIR"
    local original_hash
    original_hash=$(md5sum "$TEST_DIR/Agents.md" 2>/dev/null || md5 -q "$TEST_DIR/Agents.md")
    
    run "$GENERATE_SCRIPT" --upgrade --apply --path="$TEST_DIR"
    [ "$status" -eq 0 ]
    
    local new_hash
    new_hash=$(md5sum "$TEST_DIR/Agents.md" 2>/dev/null || md5 -q "$TEST_DIR/Agents.md")
    [ "$original_hash" != "$new_hash" ]
}

# Test 7: Project-specific content preserved after upgrade
@test "project-specific content preserved after upgrade" {
    create_agents_with_markers "$TEST_DIR"
    
    run "$GENERATE_SCRIPT" --upgrade --apply --path="$TEST_DIR"
    [ "$status" -eq 0 ]
    
    # Check project-specific content is still there
    assert_file_contains "$TEST_DIR/Agents.md" "Project-Specific Rules"
    assert_file_contains "$TEST_DIR/Agents.md" "My Custom Rule"
    assert_file_contains "$TEST_DIR/Agents.md" "feature branches"
}

# Test 8: Content before start marker preserved
@test "content before framework markers preserved" {
    create_agents_with_markers "$TEST_DIR"
    
    run "$GENERATE_SCRIPT" --upgrade --apply --path="$TEST_DIR"
    [ "$status" -eq 0 ]
    
    # Header content should be preserved
    assert_file_contains "$TEST_DIR/Agents.md" "AI Agent Guidelines"
    assert_file_contains "$TEST_DIR/Agents.md" "Generated by"
}

# Test 9: Framework content replaced with new version
@test "framework content updated during upgrade" {
    create_agents_with_markers "$TEST_DIR"
    
    run "$GENERATE_SCRIPT" --upgrade --apply --path="$TEST_DIR"
    [ "$status" -eq 0 ]
    
    # Should contain current framework version markers
    assert_file_contains "$TEST_DIR/Agents.md" "GOLDEN:framework:start"
    assert_file_contains "$TEST_DIR/Agents.md" "GOLDEN:framework:end"
}

# Test 10: Backup contains original content exactly
@test "backup contains original content" {
    create_agents_with_markers "$TEST_DIR"
    local original_content
    original_content=$(cat "$TEST_DIR/Agents.md")
    
    run "$GENERATE_SCRIPT" --upgrade --apply --path="$TEST_DIR"
    [ "$status" -eq 0 ]
    
    local backup_content
    backup_content=$(cat "$TEST_DIR/Agents.md.backup")
    [ "$original_content" = "$backup_content" ]
}

