#!/usr/bin/env bash
set -euo pipefail

# Golden Agents - Generate project-specific Agents.md from modular templates
# Repository: https://github.com/bordenet/golden-agents

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEMPLATES_DIR="$SCRIPT_DIR/templates"
REPO_URL="https://github.com/bordenet/golden-agents.git"

# Defaults
LANGUAGES=""
PROJECT_TYPE=""
OUTPUT_PATH="."
PROJECT_NAME=""
COMPACT=false
DRY_RUN=false
SYNC=false

usage() {
    cat << 'EOF'
NAME
    generate-agents.sh - Generate project-specific Agents.md from modular templates

SYNOPSIS
    generate-agents.sh [OPTIONS]
    generate-agents.sh --sync
    generate-agents.sh --language=LANG [--type=TYPE] [--path=PATH] [--compact]

DESCRIPTION
    Generates a self-contained Agents.md file by combining modular templates.
    The output file has no external dependencies and works with any AI assistant.

OPTIONS
    --language=LANG     Languages to include (comma-separated: go,python,javascript,shell,dart-flutter)
    --type=TYPE         Project type (genesis-tools, cli-tools, web-apps, mobile-apps)
    --path=PATH         Output directory (default: current directory)
    --name=NAME         Project name for header (default: directory name)
    --compact           Generate compact version (~130 lines) instead of full (~800)
    --sync              Update local templates from GitHub
    --dry-run           Print what would be generated without writing
    -h, --help          Show this help message
    -v, --version       Show version information

EXAMPLES
    # Generate for a Go CLI project
    generate-agents.sh --language=go --type=cli-tools --path=./my-cli

    # Generate compact version for a Python web app
    generate-agents.sh --language=python --type=web-apps --compact --path=./my-api

    # Update templates from GitHub
    generate-agents.sh --sync
EOF
}

version() {
    echo "golden-agents generate-agents.sh v1.1.0"
}

# Sync templates from GitHub
sync_templates() {
    echo "[INFO] Syncing templates from GitHub..."

    if [[ -d "$SCRIPT_DIR/.git" ]]; then
        cd "$SCRIPT_DIR"
        git pull --rebase origin main
        echo "[OK] Templates updated"
    else
        echo "[WARN] Not a git repo. Re-clone from: $REPO_URL"
        exit 1
    fi
}

# Parse arguments
for arg in "$@"; do
    case $arg in
        --language=*) LANGUAGES="${arg#*=}" ;;
        --type=*) PROJECT_TYPE="${arg#*=}" ;;
        --path=*) OUTPUT_PATH="${arg#*=}" ;;
        --name=*) PROJECT_NAME="${arg#*=}" ;;
        --compact) COMPACT=true ;;
        --sync) SYNC=true ;;
        --dry-run) DRY_RUN=true ;;
        -h|--help) usage; exit 0 ;;
        -v|--version) version; exit 0 ;;
        *) echo "Unknown option: $arg" >&2; usage; exit 1 ;;
    esac
done

# Handle sync mode
if [[ "$SYNC" == "true" ]]; then
    sync_templates
    exit 0
fi

# Validate
if [[ -z "$LANGUAGES" ]]; then
    echo "Error: --language is required (or use --sync to update templates)" >&2
    usage
    exit 1
fi

# Set project name from directory if not specified
if [[ -z "$PROJECT_NAME" ]]; then
    PROJECT_NAME=$(basename "$(cd "$OUTPUT_PATH" 2>/dev/null && pwd)" 2>/dev/null || echo "Project")
fi

# Get language-specific commands
get_lang_commands() {
    local lang="$1"
    case "$lang" in
        go) echo "LINT:golangci-lint run ./..."; echo "BUILD:go build ./..."; echo "TEST:go test -race -coverprofile=coverage.out ./..."; echo "COV:80" ;;
        python) echo "LINT:pylint --fail-under=9.5 ."; echo "BUILD:mypy ."; echo "TEST:pytest --cov=. --cov-report=term-missing"; echo "COV:80" ;;
        javascript) echo "LINT:npm run lint"; echo "BUILD:npm run build"; echo "TEST:npm test"; echo "COV:70" ;;
        dart-flutter) echo "LINT:flutter analyze"; echo "BUILD:flutter build"; echo "TEST:flutter test --coverage"; echo "COV:70" ;;
        shell) echo "LINT:shellcheck *.sh"; echo "BUILD:bash -n *.sh"; echo "TEST:bats test/"; echo "COV:N/A" ;;
        *) echo "LINT:# lint"; echo "BUILD:# build"; echo "TEST:# test"; echo "COV:70" ;;
    esac
}

# Generate compact Agents.md (~130 lines)
generate_compact() {
    local today
    today=$(date +%Y-%m-%d)

    IFS=',' read -ra LANG_ARRAY <<< "$LANGUAGES"
    local first_lang="${LANG_ARRAY[0]}"
    local lint_cmd build_cmd test_cmd coverage

    while IFS= read -r line; do
        case "$line" in
            LINT:*) lint_cmd="${line#LINT:}" ;;
            BUILD:*) build_cmd="${line#BUILD:}" ;;
            TEST:*) test_cmd="${line#TEST:}" ;;
            COV:*) coverage="${line#COV:}" ;;
        esac
    done < <(get_lang_commands "$first_lang")

    cat << HEADER
# AI Agent Guidelines - $PROJECT_NAME

> **Generated by**: [golden-agents](https://github.com/bordenet/golden-agents) (compact mode)
> **Last Updated**: $today
> **Languages**: $LANGUAGES
> **Type**: ${PROJECT_TYPE:-general}

Self-contained. Minimal high-signal tokens.

---

## Superpowers Integration

At the START of every conversation, run:

\`\`\`bash
node ~/.codex/superpowers-augment/superpowers-augment.js bootstrap
\`\`\`

### Key Skills

| Skill | When to Invoke |
|-------|---------------|
| \`superpowers:brainstorming\` | Before creative/feature work |
| \`superpowers:systematic-debugging\` | Before fixing bugs |
| \`superpowers:test-driven-development\` | Before writing implementation |
| \`superpowers:verification-before-completion\` | Before committing, creating PRs, or claiming done |
| \`superpowers:writing-plans\` | Before multi-step tasks |
| \`superpowers:requesting-code-review\` | Before creating PRs or merging to main |
| \`superpowers:finishing-a-development-branch\` | When completing work (merge/PR/cleanup decisions) |

**The Rule**: IF A SKILL APPLIES (even 1% chance), YOU MUST INVOKE IT.

---

## Communication Standards

- **No flattery** - Skip "Great question!" or "Excellent point!"
- **No hype words** - Avoid "revolutionary", "game-changing", "cutting-edge"
- **Evidence-based** - Cite sources, provide data, or qualify as opinion
- **Direct** - State facts without embellishment

### Banned Phrases

| Category | Avoid |
|----------|-------|
| Self-Promotion | production-grade, world-class, enterprise-ready |
| Filler | incredibly, extremely, very, really, truly |
| AI Tells | leverage, utilize, facilitate, streamline, optimize |
| Sycophancy | Happy to help!, Absolutely!, I appreciate... |

---

## Quality Gates

### Before Committing

1. **Lint**: \`$lint_cmd\`
2. **Build**: \`$build_cmd\`
3. **Test**: \`$test_cmd\`
4. **Coverage**: Minimum ${coverage}%

### Before Pushing

- [ ] All tests pass
- [ ] No linting errors
- [ ] No secrets in code
- [ ] Commit messages are descriptive

### Before Deploying

- [ ] CI shows green checkmark
- [ ] Security scan passed
- [ ] Documentation updated

HEADER

    # Add language quick reference
    echo "---"
    echo ""
    echo "## Language Quick Reference"
    echo ""

    for lang in "${LANG_ARRAY[@]}"; do
        case "$lang" in
            go)
                cat << 'LANG_GO'
### Go

- Run `golangci-lint run ./...` then `go build ./...` before committing
- 80% test coverage minimum with table-driven tests
- Error handling: wrap with context, no naked returns

LANG_GO
                ;;
            python)
                cat << 'LANG_PYTHON'
### Python

- Run `pylint --fail-under=9.5` and `mypy` before committing
- Type annotations required for all public functions
- Use `pytest` with `--cov` for coverage

LANG_PYTHON
                ;;
            javascript)
                cat << 'LANG_JS'
### JavaScript

- Run `npm run lint` and `npm run build` before committing
- Use ESLint with project config
- Prefer async/await over callbacks

LANG_JS
                ;;
            shell)
                cat << 'LANG_SHELL'
### Shell

- Run `shellcheck` on all scripts before committing
- Use `set -euo pipefail` at script start
- Quote all variables: `"$var"` not `$var`

LANG_SHELL
                ;;
            dart-flutter)
                cat << 'LANG_DART'
### Dart/Flutter

- Run `flutter analyze` before committing
- Use `AppLogger` for logging, never `print()`
- Widget tests required for UI components

LANG_DART
                ;;
        esac
    done

    cat << FOOTER
---

## Project-Specific Rules

<!-- Add project-specific guidance below -->

---

## Quick Commands

\`\`\`bash
# Lint
$lint_cmd

# Build
$build_cmd

# Test
$test_cmd
\`\`\`

---

*Generated by [golden-agents](https://github.com/bordenet/golden-agents)*
FOOTER
}

# Generate full Agents.md (~800 lines)
generate_full() {
    local today
    today=$(date +%Y-%m-%d)

    cat << HEADER
# AI Agent Guidelines - $PROJECT_NAME

> **Generated by**: [golden-agents](https://github.com/bordenet/golden-agents)
> **Last Updated**: $today
> **Languages**: $LANGUAGES
> **Type**: ${PROJECT_TYPE:-general}

This file is self-contained and portable. No external references required.

---

HEADER

    # Core guidance
    echo "## Core Guidelines"
    echo ""
    cat "$TEMPLATES_DIR/core/superpowers.md"
    echo ""
    echo "---"
    echo ""
    cat "$TEMPLATES_DIR/core/communication.md"
    echo ""
    echo "---"
    echo ""
    cat "$TEMPLATES_DIR/core/anti-slop.md"
    echo ""
    echo "---"
    echo ""

    # Workflows
    echo "## Workflows"
    echo ""
    cat "$TEMPLATES_DIR/workflows/deployment.md"
    echo ""
    echo "---"
    echo ""
    cat "$TEMPLATES_DIR/workflows/testing.md"
    echo ""
    echo "---"
    echo ""
    cat "$TEMPLATES_DIR/workflows/security.md"
    echo ""
    echo "---"
    echo ""
    cat "$TEMPLATES_DIR/workflows/build-hygiene.md"
    echo ""
    echo "---"
    echo ""
    cat "$TEMPLATES_DIR/workflows/context-management.md"
    echo ""

    # Language-specific
    echo "---"
    echo ""
    echo "## Language-Specific Guidelines"
    echo ""

    IFS=',' read -ra LANG_ARRAY <<< "$LANGUAGES"
    for lang in "${LANG_ARRAY[@]}"; do
        lang_file="$TEMPLATES_DIR/languages/${lang}.md"
        if [[ -f "$lang_file" ]]; then
            cat "$lang_file"
            echo ""
            echo "---"
            echo ""
        else
            echo "Warning: No template for language: $lang" >&2
        fi
    done

    # Project type
    if [[ -n "$PROJECT_TYPE" ]]; then
        type_file="$TEMPLATES_DIR/project-types/${PROJECT_TYPE}.md"
        if [[ -f "$type_file" ]]; then
            echo "## Project Type Guidelines"
            echo ""
            cat "$type_file"
            echo ""
        else
            echo "Warning: No template for project type: $PROJECT_TYPE" >&2
        fi
    fi

    cat << FOOTER

---

## Project-Specific Rules

<!-- Add project-specific guidance below -->

FOOTER
}

# Select generator
if [[ "$COMPACT" == "true" ]]; then
    generator="generate_compact"
    mode_label="compact"
else
    generator="generate_full"
    mode_label="full"
fi

# Output
if [[ "$DRY_RUN" == "true" ]]; then
    echo "=== DRY RUN ($mode_label mode): Would generate the following Agents.md ==="
    echo ""
    $generator
else
    mkdir -p "$OUTPUT_PATH"
    output_file="$OUTPUT_PATH/Agents.md"
    $generator > "$output_file"
    echo "Generated ($mode_label): $output_file"
    echo "Lines: $(wc -l < "$output_file")"
fi

